api {
  web_server: http://clearml.boslab.ts.net
  api_server: http://192.168.1.50:8008
  files_server: http://192.168.1.50:8081
  credentials {
    "access_key" = "EUWKWQEOXV70REQ9AZ86EHYUBUI96F"
    "secret_key" = "4g6-Ek0vR1ezWhkCzQuczKgMyQoOZGUxjcv8RyL0BvIYebFs_2_Rox-rluY8PGnPZqI"
  }
}
